- name: Register OS uname
  ansible.builtin.shell: uname
  register: os_uname

- name: "Change sysctl-settings net.core.rmem_max=2500000 (uname: {{ os_uname.stdout }})"
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: 2500000
    sysctl_set: true
    state: present
    reload: true
    ignoreerrors: true
  when: os_uname.stdout == "Linux"
